/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
module

public import PartialBalayage.Maximal.ExistingBounds
public import PartialBalayage.Maximal.SemigroupDefinitions
public import PartialBalayage.Linear.LevelSet
public import PartialBalayage.Linear.CapEnergy
public import PartialBalayage.Linear.ScalarMultiplier
public import PartialBalayage.Constants.Linear
public import PartialBalayage.Constants.Radial
public import PartialBalayage.Maximal.HeatKernel
public import PartialBalayage.Linear.RieszMultiplier
public import PartialBalayage.Linear.HessianMultiplier
public import PartialBalayage.Linear.BoundedVectorMultiplier
public import PartialBalayage.Linear.TracelessMultiplier
public import PartialBalayage.Linear.NormCap
public import PartialBalayage.Linear.CapVariational
public import PartialBalayage.Linear.KatoAveraging
public import PartialBalayage.Constants.SquareMass
public import PartialBalayage.Linear.CapComplementarity
public import PartialBalayage.Linear.DirichletDual
public import PartialBalayage.Linear.IdentityComponent
public import PartialBalayage.Linear.OrthogonalComponent
public import PartialBalayage.Linear.ProjectionSymbol
public import PartialBalayage.Linear.SobolevZeroSet
public import PartialBalayage.Maximal.RadialTangentMass
public import PartialBalayage.Maximal.HeatMajorant
public import PartialBalayage.Linear.FourierPostcomposition
public import PartialBalayage.Linear.HessianTrace
public import PartialBalayage.Linear.OperatorMultiplier
public import PartialBalayage.Linear.ProjectionMultiplier
public import PartialBalayage.Linear.VectorDirichletMass
public import PartialBalayage.Maximal.PoissonMajorant
public import PartialBalayage.Linear.SecondSobolevZeroSet
public import PartialBalayage.Linear.HessianCapEstimate
public import PartialBalayage.Linear.L1NormFunctional
public import PartialBalayage.Linear.WholeSpaceL1Norm
public import PartialBalayage.Linear.VectorDirichlet
public import PartialBalayage.Linear.VectorSobolevComposition
public import PartialBalayage.Maximal.RadialFluxComparison
public import PartialBalayage.Maximal.RadialKernelComparison
public import PartialBalayage.Maximal.HarmonicCenterLimits
public import PartialBalayage.Linear.VectorActiveMass
public import PartialBalayage.Linear.VectorBalayageFinite
public import PartialBalayage.Linear.LocalSecondSobolev
public import PartialBalayage.Linear.LocalCutoffEquation
public import PartialBalayage.Linear.LocalCutoffLaplacian
public import PartialBalayage.Linear.LocalCutoffRegularity
public import PartialBalayage.Linear.WholeSpaceMassCompactness
public import PartialBalayage.Maximal.HarmonicRadialIntegrability
public import PartialBalayage.Maximal.RadialLocalIntegrability
public import PartialBalayage.Maximal.JoinedRadialKernelIntegrability
public import PartialBalayage.Maximal.RadialPairingGeometry
public import PartialBalayage.Maximal.RadialKernelPairing
public import PartialBalayage.Maximal.SemigroupKernelPairing
public import PartialBalayage.Maximal.PlanarBoundFormula
public import PartialBalayage.Maximal.AffineRadialScaling
public import PartialBalayage.Maximal.ScaledSemigroupMajorants
public import PartialBalayage.Maximal.PoissonKernel
public import PartialBalayage.Maximal.PoissonKato
public import PartialBalayage.Linear.FourierL1L2
public import PartialBalayage.Linear.FourierEnergySplit
public import PartialBalayage.Linear.IsotropicEnergySpace
public import PartialBalayage.Linear.FourierCoercivity
public import PartialBalayage.Linear.LaplacianProduct
public import PartialBalayage.Linear.MollifierL2
public import PartialBalayage.Linear.MollifierL2Convergence
public import PartialBalayage.Linear.SobolevSpatialCutoff
public import PartialBalayage.Maximal.SquaredRadialMass
public import PartialBalayage.Maximal.SemigroupMajorantMass
public import PartialBalayage.Maximal.RadialKernelSourceBound
public import PartialBalayage.Maximal.SemigroupKernelSourceBound
public import PartialBalayage.Maximal.ScaledSemigroupSourceBound
public import PartialBalayage.Maximal.BoundedSourceTransfer
public import PartialBalayage.Maximal.L2MollifiedSource
public import PartialBalayage.Linear.L2ZeroExtension
public import PartialBalayage.Linear.SobolevZeroExtension
public import PartialBalayage.Linear.ZeroExtensionMass
public import PartialBalayage.Linear.CompactSobolevDensity
public import PartialBalayage.Linear.FourierSobolevGraph
public import PartialBalayage.Linear.SobolevDistributionGradient
public import PartialBalayage.Linear.SecondGraphWeakLaplacian
public import PartialBalayage.Linear.LocalCutoffZeroSet
public import PartialBalayage.Linear.VectorInactiveLocality
public import PartialBalayage.Linear.VectorDirichletEnergy
public import PartialBalayage.Maximal.L1KernelL2
public import PartialBalayage.Maximal.SobolevKernelSourceBound
public import PartialBalayage.Maximal.SemigroupSobolevSourceBound
public import PartialBalayage.Linear.VectorSobolevExtension
public import PartialBalayage.Linear.SobolevCoordinateMass
public import PartialBalayage.Linear.FourierDirichletEnergy
public import PartialBalayage.Linear.ScalarDirichletInterpolation
public import PartialBalayage.Linear.VectorStateCoercivity
public import PartialBalayage.Linear.UniformFiniteStateBounds
public import PartialBalayage.Linear.ZeroExtensionWeakEquation
public import PartialBalayage.Linear.ScalarPositiveObstacle
public import PartialBalayage.Linear.L2DomainRestriction
public import PartialBalayage.Linear.FiniteDensityExhaustion
public import PartialBalayage.Linear.JointWeakCompactness
public import PartialBalayage.Maximal.SemigroupTimeContinuity
public import PartialBalayage.Maximal.RationalTimeMaximal
public import PartialBalayage.Linear.WholeSpaceStateExhaustion
public import PartialBalayage.Linear.ExhaustionWeakEquation
public import PartialBalayage.Linear.WholeSpaceWeakPDE
public import PartialBalayage.Linear.WeakDirichletEnergy
public import PartialBalayage.Linear.DirichletTestClosure
public import PartialBalayage.Linear.WeakDirichletComplementarity
public import PartialBalayage.Linear.ExtendedEnergyMassIdentity
public import PartialBalayage.Linear.WholeSpaceDensityMass
public import PartialBalayage.Linear.WholeSpaceVectorBalayage
public import PartialBalayage.Linear.WholeSpaceActiveVolume
public import PartialBalayage.Linear.WholeSpaceDistributionPDE
public import PartialBalayage.Linear.GlobalBalayageActiveSet

public import PartialBalayage.Linear.ScalarStateExhaustion
public import PartialBalayage.Linear.WholeSpaceScalarPositiveBalayage
public import PartialBalayage.Maximal.CappedMaximalLevelSet

public import PartialBalayage.Linear.HessianDerivative
public import PartialBalayage.Linear.BeurlingHessianIdentity
public import PartialBalayage.Linear.HessianLinearity
public import PartialBalayage.Linear.WholeSpaceHessianRegularity
public import PartialBalayage.Linear.WholeSpaceHessianLocality
public import PartialBalayage.Linear.SobolevUnivDensity
public import PartialBalayage.Linear.SchwartzDirichletTest
public import PartialBalayage.Maximal.OneDimensionalBoundFormula
public import PartialBalayage.Maximal.ScalarSemigroupContact
public import PartialBalayage.Maximal.ScalarSemigroupOffActiveCap
public import PartialBalayage.Maximal.SemigroupNonnegL2WeakBound
public import PartialBalayage.Maximal.KernelContactCap
public import PartialBalayage.Maximal.NormTruncation
public import PartialBalayage.Maximal.KernelWeakBoundTransfer
public import PartialBalayage.Maximal.SemigroupWeakTransfer
public import PartialBalayage.Maximal.SemigroupParameters
public import PartialBalayage.Maximal.SemigroupWeakBounds

/-!
# Two partial balayage principles

The library exports nine table rows: intervals, Euclidean balls, and the six heat/Poisson bounds.
The remaining rows of the published table are tracked in `docs/DECOMPOSITION.md`.
Supporting development includes capped-decomposition level-set estimates, finite-measure vector
obstacle minimization, actual Fourier operators, Poisson and heat kernels, and exact constants.
-/
