/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
module

public import CenteredMaximal.Ball.PenaltyCompactness
public import CenteredMaximal.Ball.PenaltyEnergyBound
public import Mathlib.Analysis.SpecificLimits.Basic
public import Mathlib.Analysis.Asymptotics.Lemmas

/-!
# A bounded weak limit of capped ball penalties

Choose penalty parameters tending to zero, solve the capped penalized equations, and pass to
weak limits of the states and their density terms.
-/

@[expose] public section

noncomputable section

set_option maxHeartbeats 800000

open InnerProductSpace MeasureTheory Metric Filter Topology
open scoped RealInnerProductSpace NNReal ENNReal

namespace CenteredMaximal.Ball.DirichletSobolev

variable {n : ℕ}

/-- A positive penalty parameter tending to zero. -/
def ballPenaltyEpsilon (k : ℕ) : ℝ := ((k + 1 : ℕ) : ℝ)⁻¹

theorem ballPenaltyEpsilon_pos (k : ℕ) : 0 < ballPenaltyEpsilon k := by
  unfold ballPenaltyEpsilon
  positivity

theorem ballPenaltyEpsilon_tendsto_zero :
    Tendsto ballPenaltyEpsilon atTop (𝓝 0) := by
  convert (tendsto_one_div_add_atTop_nhds_zero_nat (𝕜 := ℝ)) using 1
  funext k
  simp [ballPenaltyEpsilon, Nat.cast_add]

/-- The density generated by the negative-part penalty. -/
def ballPenaltyDensity
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (k : ℕ) (U : H01 (ball center R)) : L2D (ball center R) :=
  (ballPenaltyEpsilon k)⁻¹ • Lp.negPart (valueEmbedding (ball center R) U)

theorem ballPenaltyEpsilon_smul_density
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (k : ℕ) (U : H01 (ball center R)) :
    ballPenaltyEpsilon k • ballPenaltyDensity center R k U =
      Lp.negPart (valueEmbedding (ball center R) U) := by
  simp [ballPenaltyDensity, smul_smul,
    mul_inv_cancel₀ (ballPenaltyEpsilon_pos k).ne']

/-- The penalty density is nonnegative as an `L²` function. -/
theorem ballPenaltyDensity_nonneg
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (k : ℕ) (U : H01 (ball center R)) :
    0 ≤ ballPenaltyDensity center R k U := by
  rw [← Lp.coeFn_nonneg]
  filter_upwards [Lp.coeFn_zero ℝ 2 (volume.restrict (ball center R)),
    Lp.coeFn_smul (ballPenaltyEpsilon k)⁻¹
      (Lp.negPart (valueEmbedding (ball center R) U)),
    Lp.coeFn_negPart_eq_max (valueEmbedding (ball center R) U)]
      with x hzero hsmul hneg
  change (0 : ℝ) ≤ (ballPenaltyDensity center R k U) x
  simp only [ballPenaltyDensity, hsmul, Pi.smul_apply, smul_eq_mul, hneg]
  exact mul_nonneg (inv_pos.mpr (ballPenaltyEpsilon_pos k)).le (le_max_right _ _)

/-- The pointwise cap from the penalty estimate is an order bound by the constant `L²` cap. -/
theorem ballPenaltyDensity_le_cap
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (k : ℕ) (U : H01 (ball center R)) (κ : ℝ)
    (hcap : ∀ᵐ x ∂(volume.restrict (ball center R)),
      (ballPenaltyDensity center R k U) x ≤ κ) :
    ballPenaltyDensity center R k U ≤ κ • ballUnitL2 center R := by
  rw [← Lp.coeFn_le]
  filter_upwards [hcap, Lp.coeFn_smul κ (ballUnitL2 center R),
    ballUnitL2_coeFn center R] with x hx hsmul hunit
  simpa only [hsmul, Pi.smul_apply, smul_eq_mul, hunit, mul_one] using hx

/-- Along any increasing subsequence, the negative part of the penalized state vanishes in
`L²`: it is the capped density multiplied by the vanishing penalty parameter. -/
theorem ball_penalty_negPart_tendsto_zero
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (U : ℕ → H01 (ball center R)) (κ : ℝ)
    (hcap : ∀ k, ∀ᵐ x ∂(volume.restrict (ball center R)),
      (ballPenaltyDensity center R k (U k)) x ≤ κ)
    (χ : ℕ → ℕ) (hχ : StrictMono χ) :
    Tendsto (fun j => Lp.negPart (valueEmbedding (ball center R) (U (χ j))))
      atTop (𝓝 0) := by
  let K : L2D (ball center R) := κ • ballUnitL2 center R
  have hbdd : IsBoundedUnder (· ≤ ·) atTop
      (norm ∘ (fun j => ballPenaltyDensity center R (χ j) (U (χ j)))) := by
    apply Filter.isBoundedUnder_of
    refine ⟨‖K‖, ?_⟩
    intro j
    exact norm_l2_le_of_nonneg_le _ K
      (ballPenaltyDensity_nonneg center R (χ j) (U (χ j)))
      (ballPenaltyDensity_le_cap center R (χ j) (U (χ j)) κ (hcap (χ j)))
  have hε : Tendsto (fun j => ballPenaltyEpsilon (χ j)) atTop (𝓝 0) :=
    ballPenaltyEpsilon_tendsto_zero.comp hχ.tendsto_atTop
  have hsmul := NormedField.tendsto_zero_smul_of_tendsto_zero_of_bounded hε hbdd
  convert hsmul using 1
  funext j
  exact (ballPenaltyEpsilon_smul_density center R (χ j) (U (χ j))).symm

/-- Select one capped solution for each penalty parameter, with one common state norm bound. -/
theorem exists_ball_penalized_sequence
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (f : L2D (ball center R)) (κ : ℝ) (hκ : 0 ≤ κ)
    (hf : ∀ᵐ x ∂(volume.restrict (ball center R)), 0 ≤ f x) :
    ∃ C : ℝ, ∃ U : ℕ → H01 (ball center R),
      (∀ k, ‖U k‖ ≤ C) ∧
      (∀ k, ∀ V : H01 (ball center R),
        laplaceBilin (ball center R) (U k) V =
          l2Functional (ball center R) f V -
            κ * l2Functional (ball center R) (ballUnitL2 center R) V +
            ⟪ballPenaltyDensity center R k (U k),
              valueEmbedding (ball center R) V⟫_ℝ) ∧
      (∀ k, ∀ᵐ x ∂(volume.restrict (ball center R)),
        (ballPenaltyDensity center R k (U k)) x ≤ κ) := by
  obtain ⟨C, hC⟩ := exists_uniform_ball_penalized_norm_bound center R f κ
  have hsol (k : ℕ) := exists_ball_penalized_solution_capped center R f κ
    (ballPenaltyEpsilon k) hκ (ballPenaltyEpsilon_pos k) hf
  choose U hUweak hUcap using hsol
  refine ⟨C, U, (fun k => hC (ballPenaltyEpsilon k) (ballPenaltyEpsilon_pos k)
    (U k) (hUweak k)), ?_, ?_⟩
  · intro k V
    have h := hUweak k V
    simpa only [ballPenaltyDensity, real_inner_smul_left] using h
  · intro k
    filter_upwards [hUcap k,
      Lp.coeFn_smul (ballPenaltyEpsilon k)⁻¹
        (Lp.negPart (valueEmbedding (ball center R) (U k)))] with x hx hsmul
    simpa only [ballPenaltyDensity, hsmul, Pi.smul_apply, smul_eq_mul] using hx

/-- A uniformly bounded capped penalty sequence has a weak state and density limit obeying
the Dirichlet equation. -/
theorem ball_penalized_weak_limit_of_sequence
    (center : EuclideanSpace ℝ (Fin (n + 1))) (R : ℝ)
    (f : L2D (ball center R)) (κ : ℝ)
    (U : ℕ → H01 (ball center R)) (C : ℝ)
    (hbound : ∀ k, ‖U k‖ ≤ C)
    (hweak : ∀ k, ∀ V : H01 (ball center R),
      laplaceBilin (ball center R) (U k) V =
        l2Functional (ball center R) f V -
          κ * l2Functional (ball center R) (ballUnitL2 center R) V +
          ⟪ballPenaltyDensity center R k (U k),
            valueEmbedding (ball center R) V⟫_ℝ)
    (hcap : ∀ k, ∀ᵐ x ∂(volume.restrict (ball center R)),
      (ballPenaltyDensity center R k (U k)) x ≤ κ) :
    ∃ Ulim : H01 (ball center R), ∃ νlim : L2D (ball center R),
      ∃ χ : ℕ → ℕ,
        (0 ≤ νlim ∧ νlim ≤ κ • ballUnitL2 center R) ∧
        StrictMono χ ∧
        Tendsto (fun k => toWeakSpace ℝ (H01 (ball center R)) (U (χ k))) atTop
          (𝓝 (toWeakSpace ℝ (H01 (ball center R)) Ulim)) ∧
        Tendsto (fun k => toWeakSpace ℝ (L2D (ball center R))
          (ballPenaltyDensity center R (χ k) (U (χ k)))) atTop
          (𝓝 (toWeakSpace ℝ (L2D (ball center R)) νlim)) ∧
        (∀ V : H01 (ball center R),
          laplaceBilin (ball center R) Ulim V =
            l2Functional (ball center R) f V -
              κ * l2Functional (ball center R) (ballUnitL2 center R) V +
              ⟪νlim, valueEmbedding (ball center R) V⟫_ℝ) := by
  let D := ball center R
  let K : L2D D := κ • ballUnitL2 center R
  let ν : ℕ → L2D D := fun k => ballPenaltyDensity center R k (U k)
  let source : H01 D →L[ℝ] ℝ :=
    l2Functional D f - κ • l2Functional D (ballUnitL2 center R)
  letI : TopologicalSpace.SeparableSpace (H01 D) :=
    CenteredMaximal.Ball.separableSpace_H01_ball center R
  have hν : ∀ k, 0 ≤ ν k ∧ ν k ≤ K := by
    intro k
    exact ⟨ballPenaltyDensity_nonneg center R k (U k),
      ballPenaltyDensity_le_cap center R k (U k) κ (hcap k)⟩
  have hνbound : ∀ k, ‖ν k‖ ≤ ‖K‖ := by
    intro k
    exact norm_l2_le_of_nonneg_le (ν k) K (hν k).1 (hν k).2
  have heq : ∀ k V,
      laplaceBilin D (U k) V = source V + ⟪ν k, valueEmbedding D V⟫_ℝ := by
    intro k V
    simpa only [D, source, sub_apply, smul_apply, smul_eq_mul, ν] using hweak k V
  obtain ⟨Ulim, νlim, χ, hνlim, hχ, hUlim, hνlimweak, hlimEq⟩ :=
    exists_weak_limit_of_bounded_penalized_equations
      (laplaceBilin D) (valueEmbedding D) source U ν K C ‖K‖
      hbound hνbound hν heq
  exact ⟨Ulim, νlim, χ, hνlim, hχ, hUlim, hνlimweak,
    fun V => by simpa only [D, source, sub_apply, smul_apply, smul_eq_mul] using hlimEq V⟩

end CenteredMaximal.Ball.DirichletSobolev
